### ISSUE TITLE
Curvas do modelos não estão sendo atualizadas

### ISSUE THREAD

**Issue by fccoelho** [NAMD/covidash#12]
Quando mudo os parâmetros do modelo, as curvas não mudam. Talvez o valor dos parâmetros não estejam sendo atualizados.

**Comment by rhenanbartels** [comment]
@fccoelho, rodando no ambiente local o modelo está atualizando. O que será que pode estar acontencendo?

**Comment by fccoelho** [comment]
Resolvido. Fechando.
