### ISSUE TITLE
Adicionar plot de curvas alinhadas

### ISSUE THREAD

**Issue by fccoelho** [NAMD/covidash#18]
Criar para os estados brasileiros e para países uma visualização de curvas alinhadas pelo dia em que cruzam 100 casos. Ver código do notebook `Modelo_SEIR`.
![image](https://user-images.githubusercontent.com/140123/78782285-26126e80-7978-11ea-8960-78a95dc8e5b3.png)

**Comment by linneuholanda** [comment]
Alguém já está fazendo isto? Posso pegar?
