### ISSUE TITLE
Problema ao instalar as dependências pip

### ISSUE THREAD

**Issue by nahumsa** [NAMD/covidash#2]
Ao instalar as dependências com `pip install -r requirements.txt` encontro dois erros: 

`UserWarning: Unable to determine GEOS version. Ensure you have 3.3.3 or later installed, or installation may fail.`
` Proj 4.9.0 must be installed.`

O que fiz para contornar isso no Ubuntu 18.04 foi: 

!apt-get install libproj-dev proj-data proj-bin  
!apt-get install libgeos-dev

**Comment by fccoelho** [comment]
é isso mesmo @nahumsa  . Documente isso no README e podemos fechar esta issue
