### ISSUE TITLE
Criar um novo branch para deploy

### ISSUE THREAD

**Issue by fccoelho** [NAMD/covidash#25]
Pessoal, vou criar um novo branch deploy mantendo só os arquivos essenciais para o funcionamento no Heroku. Assim o deploy fica mais leve. Continuem fazendo PR para o Master e vou fazendo o merge em deploy antes de atualizar o Heroku.

**Comment by fccoelho** [comment]
Humm... esta ideia pode ser meio trabalhosa na hora de fazer merge, sem trazer junto os arquivos indesejados do branch master... Alguma sugestão @turicas?

**Comment by turicas** [comment]
Não sei se adianta, a não ser que seja um branch sem commit em comum com a árvore atual, senão ele vai enviar todos os commits do histórico.
O que você gostaria de melhorar? O tempo de push tem a ver só com os diffs dos novos commits. O tempo de build da imagem tem a ver com os requirements e como eles estão sendo instalados (binários /source e usando ou não o cache). O tamanho final da imagem tem a ver com o que está no repositório e os requirements.

**Comment by fccoelho** [comment]
Não sei se tem alguma limitação de tamanho da imagem no heroku
Minha intenção era tentar evitar misturar arquivos que não tem nada a ver com o dashboard com o Dashboard. Talvez a saída correta seja criar um repositório separado para as análises nos notebooks

**Comment by turicas** [comment]
Talvez eles possam conviver no mesmo repositório se as pastas estiverem organizadas de modo a um não interferir um com o outro e caso os notebooks + dados + imagens no repositório não sejam excessivamente grandes. Uma ação fácil que já diminuiria o tempo de build e tamanho da imagem final é ter um requirements separado para cada um, assim ao fazer deployment no Heroku o script de build só instalará as dependências do dashboard (ou seja, `requirements.txt` com dependeências do dashboard e `notebooks/requirements.txt` com dependências dos notebooks).

**Comment by fccoelho** [comment]
Não sei se tem alguma limitação de tamanho da imagem no heroku
Minha intenção era tentar evitar misturar arquivos que não tem nada a ver com o dashboard com o Dashboard. Talvez a saída correta seja criar um repositório separado para as análises nos notebooks
