### ISSUE TITLE
Adicionar Número de Hospitalizações e de Mortos atrelados ao modelo

### ISSUE THREAD

**Issue by fccoelho** [NAMD/covidash#34]
O página do modelo precisa  mostrar alguns números importantes que resumam a situação, atualizados dinâmicamente.

**Comment by rhenanbartels** [comment]
Oi @fccoelho, pode dar mais detalhe sobre os dados que precisam estar na página do modelo? Posso pegar essa issue.

**Comment by fccoelho** [comment]
Basicamente precisamos calcular estes valores a partir dos resultados da simulação e atualizá-los como acontece agora com o R0.

- Hospitalizações totais é o último valor da curva de Hospitalizações acumuladas.
- Número de hospitalizações no Pico
- Dia do pico de hosp. , etc.
- Limiar epidêmico: 1/R0 (linha horizontal)
- etc.
Amanhã vou adicionar um compartimento para o acumulo das mortes.
outro bom exemplo é esse:https://gabgoh.github.io/COVID/index.html

**Comment by fccoelho** [comment]
Já Adicionei mortes acumuladas ao modelo.
