### ISSUE TITLE
Criar app básico usando o Streamlit

### ISSUE THREAD

**Issue by fccoelho** [NAMD/covidash#4]
Precisamos de uma App ond possamos plugar nossas análises e visualizações
Decidimos pelo [streamlit.io](https://streamlit.io).

**Comment by rhenanbartels** [comment]
Olá pessoal, comecei a olhar como iniciar o dashboard com streamlit e se formos usar o Heroku, vamos precisar fazer algumas configurações extras.

O projeto depende dos seguintes pacotes que precisam ser adicionados durante o build do app:

- libproj-dev proj-data proj-bin
- ibgeos-dev

Para instalar os pacotes precisamos executar os seguintes comandos e criar os seguintes arquivos:

```bash
heroku buildpacks:add --index 1 heroku-community/apt
```

Criar um **Aptfile**

```bash

vim Aptfile
```
```
libproj-dev proj-data proj-bin

libgeos-dev
```

Coloquei o `app.py` responsável pelo lógica do dashboard dentro do diretório `dashboard`

A partir daqui conseguimos adicionar a modelagem no arquivo `dashboard/app.py`
