### ISSUE TITLE
Criar módulo com as equações e funções utilitárias 

### ISSUE THREAD

**Issue by rhenanbartels** [NAMD/covidash#6]
Como vamos replicar o código das equações do modelo no Jupyter notebook e no dashboard Streamlit, acho que vale a pena criar um pacote python com as equações e as funções utilitárias e importá-las tanto no notebook, quanto no dashboard

**Comment by fccoelho** [comment]
Sim é uma boa idéia. Proponho implementarmos os modelos na minha biblioteca [Epimodels](https://github.com/fccoelho/epimodels) Assim os modelos ficam pip instaláveis.

As demais funções utilitárias podemos manter em um módulo acessório neste projeto mesmo.

**Comment by rhenanbartels** [comment]
Oi @fccoelho, tomei a liberdade de criar um módulo temporário para os modelos
`seqihr` e `seqiahr`. Desta forma, imagino que  Jupyter notebook não irá quebrar e não
adiciono funções que não seguem a mesma API da classe `ContinousModel`. 

Depois, se for o caso, podemos refatorar para adicionar de forma permanente os modelos
à biblioteca [epimodels](https://github.com/fccoelho/epimodels)

Do jeito que está, para importar os modelos é preciso fazer:

```python
from epimodels.covid import seqiahr
```

**Comment by fccoelho** [comment]
Tranquilo @rhenanbartels , hoje passei o dia analisando outros dados e não consegui pegar neste código amanhã dou uma gás nisso!
