### ISSUE TITLE
Visualização com Pydeck

### ISSUE THREAD

**Issue by fccoelho** [NAMD/covidash#9]
Precisamos criar uma visualização Geo usando o [Pydeck](https://deckgl.readthedocs.io/en/latest/layer.html). Temos várias análise geográficas que precisam de uma representação interativa eficiente.

Há um bom exemplo [aqui](https://github.com/streamlit/demo-uber-nyc-pickups/blob/master/app.py).

**Comment by nahumsa** [comment]
Adicionei um Layer com os casos para cada estado, centrados nas capitais. 
Estou com dificuldade com as barras, amanhã tentarei consertar.

**Comment by fccoelho** [comment]
@nahumsa fiz o deploy, mas mesmo tendo adicionado o meu token do mapbox, continua dando mensagem que que o token não fornecido.

**Comment by nahumsa** [comment]
Eu consegui ver o mapbox ao entrar no aplicativo. Mas os dados não estão aparecendo, estou tentando consertar aqui.
